services:
  # --- Reverse Proxy ---
  nginx-proxy:
    build:
      context: ./nginx-server
    container_name: nginx-proxy
    restart: always
    ports:
      - '80:80'
      - '443:443'
    networks:
      - web
    volumes:
      - certs:/etc/nginx/certs
      - vhostd:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html

  # --- Tu aplicación .NET ---
  pagina:
    build:
      context: ./Desarrollo_Web
      dockerfile: Dockerfile
    container_name: demon-pagina
    expose:
      - '80'
    environment:
      - ASPNETCORE_URLS=http://+:80
      - VIRTUAL_HOST=app2.fazttech.store
      - LETSENCRYPT_HOST=app2.fazttech.store
      - LETSENCRYPT_EMAIL=amateod2@miumg.edu.gt
    networks:
      - web

networks:
  web:
    external: true
    name: web

volumes:
  certs:
  html:
  vhostd:
