version: '3'

services:
  congreso-frontend:
    build:
      context: ./Desarrollo_Web
      dockerfile: Dockerfile
    restart: always
    environment:
      - VIRTUAL_HOST=app2.fazttech.store
      - LETSENCRYPT_HOST=app2.fazttech.store
      - LETSENCRYPT_EMAIL=amateod2@miumg.edu.gt
    networks:
      - web
    expose:
      - '80'

networks:
  web:
    external: true
