version: '3.8'

services:
  app:
    build:
      context: ./Desarrollo_Web
      dockerfile: Dockerfile
    container_name: demonslayer-app
    expose:
      - 7211
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    networks:
      - demonslayer-network

  nginx:
    build:
      context: ./nginx-server
      dockerfile: Dockerfile
    container_name: demonslayer-nginx
    ports:
      - '8080' # Externa:8080 -> Interna:8080
    depends_on:
      - app
    networks:
      - demonslayer-network

networks:
  demonslayer-network:
    driver: bridge
