services:
  app:
    build:
      context: ./Desarrollo_Web
      dockerfile: Dockerfile
    container_name: demonslayer-app
    expose:
      - 7211
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    networks:
      - demonslayer_network # Con underscore
    restart: unless-stopped

  nginx:
    build:
      context: ./nginx-server
      dockerfile: Dockerfile
    container_name: demonslayer-nginx
    ports:
      - '8080'
      - '443'
    volumes:
      - ./letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - app
    networks:
      - demonslayer_network # Con underscore
    restart: unless-stopped

networks:
  demonslayer_network: # Con underscore
    driver: bridge
