version: '3.8'

services:
  # --- NGINX Reverse Proxy ---
  nginx:
    build:
      context: ./nginx-server
      dockerfile: Dockerfile
    container_name: nginx-proxy
    ports:
      - '80:80'
      - '443:443' # Para cuando agregues SSL
    volumes:
      - ./ssl-certs:/etc/ssl/certs # Para certificados SSL
      - ./ssl-private:/etc/ssl/private
    depends_on:
      - pagina
    networks:
      - web

  # --- Tu aplicación .NET ---
  pagina:
    build:
      context: ./Desarrollo_Web
      dockerfile: Dockerfile
    container_name: demon-pagina
    expose:
      - '8080'
    environment:
      - ASPNETCORE_URLS=http://+:8080
    networks:
      - web

networks:
  web:
    external: true
    name: web
