version: '3.9'

services:
  proyecto-app:
    build:
      context: ./Desarrollo_Web
      dockerfile: Dockerfile
    restart: always
    container_name: proyecto-app
    ports:
      - '8080'
    depends_on:
      - sqlserver
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=FreeLancer;User=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=True;

      - VIRTUAL_HOST=proyecto-app.fazttech.store
      - LETSENCRYPT_HOST=proyecto-app.fazttech.store
      - LETSENCRYPT_EMAIL=amateod2@miumg.edu.gt

    networks:
      - web

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: proyecto-app-sql
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong!Passw0rd
    ports:
      - '1433:1433'
    volumes:
      - sql_data:/var/opt/mssql
    networks:
      - web

networks:
  web:
    external: true

volumes:
  sql_data: